### ISSUE TITLE
Error message for chr_array.py

### ISSUE THREAD

**Issue by lsantuari** [GooglingTheCancerGenome/CNN#13]
```
+ python chr_array.py --bam /hpc/cog_bioinf/ridder/users/lsantuari/Git/DeepSV_refactoring/CNN/data/test/chr22.bam --chr chr22 --twobit /hpc/cog_bioinf/ridder/users/lsantuari/Git/DeepSV_refactoring/CNN/data/test/chr22.2bit --map /hpc/cog_bioinf/ridder/users/lsantuari/Git/DeepSV_refactoring/CNN/data/test/chr22.bw --out chr_array.npy --outputpath . --logfile chr_array.log
Error.  nthreads cannot be larger than environment variable "NUMEXPR_MAX_THREADS" (64)Traceback (most recent call last):
  File "chr_array.py", line 346, in <module>
    main()
  File "chr_array.py", line 340, in main
    cmd_name=cmd_name
  File "chr_array.py", line 191, in create_hdf5
    chr_array[idx, channel_index] = vals
  File "bcolz/carray_ext.pyx", line 2128, in bcolz.carray_ext.carray.__setitem__
ValueError: could not broadcast input array from shape (1179) into shape (46)
```

**Comment by arnikz** [comment]
First, let's make this work completely with `numpy` arrays using a reduced dataset #11.
