### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/CNN#79]
```
$ python ./Ns_to_bed.py 
Traceback (most recent call last):
  File "./Ns_to_bed.py", line 55, in <module>
    main()
  File "./Ns_to_bed.py", line 51, in main
    get_regions(args.twobit, args.chrlist.split(','), args.bed)
  File "./Ns_to_bed.py", line 7, in get_regions
    genome = twobit.TwoBitFile(twobitfile)
  File "/home/arni/miniconda3/envs/sv-channels/lib/python3.8/site-packages/twobitreader/__init__.py", line 251, in __init__
    raise IOError(ENOENT, strerror(ENOENT), foo)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lsantuari/Documents/Projects/GTCG/2bit/hs37d5.2bit
```
```
$ python Ns_to_bed.py -b ../../data/reference_N_regions.bed -t ../../data/test.2bit
Traceback (most recent call last):
  File "Ns_to_bed.py", line 55, in <module>
    main()
  File "Ns_to_bed.py", line 51, in main
    get_regions(args.twobit, args.chrlist.split(','), args.bed)
  File "Ns_to_bed.py", line 12, in get_regions
    seq = str(genome[c])
KeyError: '1'
```

**Comment by arnikz** [comment]
See #80.
